# Generated by Django 5.1.5 on 2026-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("title", models.CharField(blank=True, max_length=140)),
                ("photo_url", models.URLField(blank=True)),
                ("bio_en", models.TextField(blank=True)),
                ("bio_es", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("license_number", models.CharField(blank=True, max_length=40)),
                (
                    "specialties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["Luxury Estates", "New Development"]',
                    ),
                ),
                (
                    "neighborhoods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["Beverly Hills", "Bel Air"]',
                    ),
                ),
                (
                    "career_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"total_sales_volume": "$412M", "homes_sold": 168, "years_experience": 14}',
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
