# Generated by Django 5.1.5 on 2026-08-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="CA", max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("buy", "For Sale"), ("rent", "For Rent")],
                        default="buy",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("open_house", "Open House"),
                            ("price_reduced", "Price Reduced"),
                            ("pending", "Pending"),
                            ("coming_soon", "Coming Soon"),
                            ("sold", "Sold"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family", "Single Family"),
                            ("condo", "Condo"),
                            ("townhome", "Townhome"),
                            ("estate", "Estate"),
                        ],
                        default="single_family",
                        max_length=20,
                    ),
                ),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "bathrooms",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("square_footage", models.PositiveIntegerField(default=0)),
                (
                    "lot_size",
                    models.PositiveIntegerField(default=0, help_text="Square feet"),
                ),
                ("year_built", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "hoa_fee",
                    models.PositiveIntegerField(
                        blank=True, help_text="Monthly, USD", null=True
                    ),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_es", models.TextField(blank=True)),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["Canyon-to-ocean views"]',
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["Pool", "3-Car Garage"]',
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("open_house_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="agents.agent",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL. Leave blank if uploading a file below.",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(blank=True, null=True, upload_to="properties/"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Also used as alt text (spec §18, ADA)",
                        max_length=200,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_id",
                    models.SlugField(
                        help_text="Unique within this property, e.g. 'living-room'",
                        max_length=60,
                    ),
                ),
                ("room_name", models.CharField(max_length=80)),
                (
                    "panorama_url",
                    models.URLField(blank=True, help_text="Equirectangular image URL"),
                ),
                (
                    "panorama_file",
                    models.ImageField(blank=True, null=True, upload_to="tours/"),
                ),
                ("initial_yaw", models.FloatField(default=0)),
                ("initial_pitch", models.FloatField(default=0)),
                (
                    "hotspots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. [{"yaw": 120, "pitch": -5, "target": "kitchen", "text": "Kitchen"}]',
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_scenes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("property", "scene_id")},
            },
        ),
    ]
