# Generated by Django 5.1.5 on 2026-08-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("showing", "Schedule a Showing"),
                            ("question", "Ask a Question"),
                            ("valuation", "AI Home Valuation"),
                            ("contact", "General Contact"),
                        ],
                        default="contact",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.CharField(blank=True, max_length=40)),
                (
                    "valuation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"address": "...", "sqft": 2800, "zone": "beverly-hills", "condition": "updated", "estimated_min": 1200000, "estimated_max": 1350000}',
                    ),
                ),
                ("consent_marketing", models.BooleanField(default=False)),
                ("source_locale", models.CharField(blank=True, max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="agents.agent",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
