# Generated by Django 5.1.5 on 2026-08-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("excerpt_en", models.TextField(blank=True)),
                ("excerpt_es", models.TextField(blank=True)),
                (
                    "body_en",
                    models.TextField(
                        blank=True,
                        help_text="Markdown-ish; blank line separates paragraphs",
                    ),
                ),
                ("body_es", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("market_report", "Market Report"),
                            ("neighborhood_guide", "Neighborhood Guide"),
                            ("buying_guide", "Buying Guide"),
                            ("selling_guide", "Selling Guide"),
                        ],
                        default="market_report",
                        max_length=24,
                    ),
                ),
                ("read_minutes", models.PositiveSmallIntegerField(default=4)),
                ("published_at", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
