# Generated by Django 5.1.5 on 2026-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("state", models.CharField(default="CA", max_length=2)),
                ("hero_image", models.URLField(blank=True)),
                ("tagline_en", models.CharField(blank=True, max_length=200)),
                ("tagline_es", models.CharField(blank=True, max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_es", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "market_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"median_price": 4250000, "active_listings": 128, "median_dom": 41, "price_per_sqft": 1210}',
                    ),
                ),
                (
                    "lifestyle_info",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. [{"category": "Dining", "items": ["..."]}]',
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "communities",
                "ordering": ["order", "name"],
            },
        ),
    ]
